config/routes.rb
Rails.application.routes.draw do
  
  resources :leagues
  resources :leagues, only: [:show] do
    resources :teams, only: [:show, :index, :new, :create]
  end

  resources :roster_spots, only: [:create, :destroy, :update]

  resources :players

  resources :teams

  get '/reports', to: 'reports#index'
  get '/efficient', to: 'reports#most_efficient'
  get '/valuable', to: 'reports#most_valuable'
  get '/popular_leagues', to: 'reports#most_popular_leagues'
  get '/popular_players', to: 'reports#most_popular_players'
  get '/highest_scoring', to: 'reports#highest_scoring_players'
  post '/join_league', to: 'teams#join_league'
  post '/leave_league', to: 'teams#leave_league'
  post '/update_all_players', to: 'players#update_all'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'teams#index'

end

app/models/player.rb
require 'open-uri'

class Player < ActiveRecord::Base
  has_many :roster_spots, dependent: :destroy
  has_many :teams, through: :roster_spots
  validates_presence_of :player_url
  validate :valid_url
  after_save :update_info

  def valid_url
    if !self.player_url.include?("http://www.basketball-reference.com/players")
      errors.add(:player_url, "is not a valid Basketball Reference Player URL")
    end
  end

  def calculate_score
    self.score = points + (2 * (rebounds + assists + blocks + steals))
    self.save
  end

  def calculate_new_score(hash)
    hash[:points].to_i + (2 * (hash[:rebounds].to_i + hash[:assists].to_i + hash[:blocks].to_i + hash[:steals].to_i))
  end

  def self.update_all_players
    Player.all.find_each(batch_size: 10) do |player|
      player.update_info
    end
  end

  def update_info
    old_score = self.score
    info_hash = self.get_player_info
    info_hash[:score] = self.calculate_new_score(info_hash)
    if old_score != info_hash[:score]
      self.update(info_hash)
      self.set_value
      self.update_teams_score(old_score, self.score)
    end
  end

  def set_value
    self.update(value:(self.score / (self.salary.to_f / 1000000)).round(2))
  end

  def status(team)
    spot = self.roster_spots.where(team_id: team.id).first
    spot.starter ? "Starter" : "Benched"
  end

  def set_status(team, lineup_status)
    spot = self.roster_spots.where(team_id: team.id).first
    spot.starter = lineup_status
    spot.save
  end

  def self.most_valuable_players
    self.order(value: :desc).limit(10)
  end

  def self.most_popular_players
    Player.all.max_by(10) do |player|
      player.teams.count
    end
  end

  def self.highest_scoring_players
    self.order(score: :desc).limit(10)
  end

  def self.most_valuable
    self.order(value: :desc).limit(1)
  end

  def self.least_valuable
    self.order(value: :asc).limit(1)
  end

  def get_player_info
    url = self.player_url
    page = Nokogiri::HTML(open(url))

    name = page.css("h1").first.text
    
    salary = get_salary(page)

    season = page.css("table#totals tr.full_table").last
    stats_array = array_maker(season)
    info_hash = {
      points: stats_array[30].to_i, 
      assists: stats_array[25].to_i, 
      rebounds: stats_array[24].to_i, 
      blocks: stats_array[27].to_i, 
      steals: stats_array[26].to_i, 
      games_played: stats_array[6].to_i, 
      position: stats_array[5],
      salary: salary.to_i,
      name: name
    }
    return info_hash
  end

  def get_salary(page)
    contract = page.css("table#contract tr").last
    contract_array = array_maker(contract)
    salary = contract_array[2]
    salary.delete("$ ,").to_i
  end

  def array_maker(element)
    element.text.split("\n").map {|x| x.strip}
  end

  def update_teams_score(old_score, new_score)
    difference = new_score - old_score
    score = 0
    self.roster_spots.each do |roster_spot|
      if roster_spot.starter
        score = roster_spot.team.score + difference
      else
        score = roster_spot.team.score + (difference / 2)
      end
      roster_spot.team.update(score: score, efficiency: roster_spot.team.calculate_efficiency)
    end
  end

  def next
    Player.where("id > ?", self.id).first
  end

  def prev
    Player.where("id < ?", self.id).last
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  load_and_authorize_resource
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  def index
    if params[:affordable] && @user = current_user
      @players = @user.team.affordable
    elsif params[:available] && @user = current_user
      @players = @user.team.available
    else
      @players = Player.order(score: :desc)
    end

    respond_to do |format|
      format.html { render :index }
      format.json { render json: @players}
    end
  end

  def show
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @player}
    end
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.find_or_initialize_by(player_params)
    if @player.save
      render json: @player, status: 201
    else
      flash.now[:alert] = @player.errors.full_messages.first
      render :new
    end
  end

  def edit

  end

  def update
    @player.update(player_params)
    redirect_to @player
  end

  def destroy
    @player.destroy
    redirect_to players_path
  end

  def update_all
    if current_user.admin?
      PlayersWorker.perform_async
      redirect_to players_path, notice: "Updating all players in the background."
    else
      redirect_to players_path, alert: "You're not allowed to do that."
    end
  end

  private

  def player_params
    params.require(:player).permit(:player_url)
  end

  def set_player
    @player = Player.find(params[:id])
  end
end

app/helpers/players_helper.rb
module PlayersHelper

  def add_player_column(player)
    if current_user.team.players.include?(player)
      "This player is on your team"
    else
      link_to "Add Player", roster_spots_path(player_id: player.id), method: :post, class: "btn btn-success btn-xs"
    end
  end

  def has_team_options
    if has_team_check?
      render 'players/has_team_options'
    end
  end

  def admin_options
    if admin_check?
      render 'players/admin_player_options'
    end
  end

  def display_salary_remaining
    if has_team_check?
      content_tag :h4, "You have #{number_to_currency(current_user.team.salary_remaining, precision: 0)} to add players."
    end
  end

end

app/views/players/_admin_player_options.html.erb
<%= link_to "Create Player", new_player_path, class: "btn btn-sm btn-primary" %>
<%= link_to "Update All Players", update_all_players_path, class: "btn btn-sm btn-primary", method: :post %>

app/views/players/_form.html.erb
<%= form_for @player, html: {id: "player_form" } do |f| %>
  <%= f.label :player_url, "Player Profile URL" %>
  <%= f.text_field :player_url, id: "playerUrl" %>
  <%= f.submit class: 'btn btn-success' %>
<% end %>

app/views/players/_has_team_options.html.erb
<%= link_to "Show All", players_path, class: "btn btn-primary btn-sm" %>
<%= link_to "Show Players You Can Afford", players_path(affordable: true), class: "btn btn-primary btn-sm" %>
<%= link_to "Show Available Players", players_path(available: true), class: "btn btn-primary btn-sm" %>
<%= display_salary_remaining %>

app/views/players/_player.html.erb
<tr>
  <td><%= link_to player.name, player %></td>
  <td><%= player.position %></td>
  <td><%= player.score %></td>
  <td><%= number_to_currency(player.salary, precision: 0) %></td>
  <td><%= player.value %></td>
  <td>On <%= pluralize(player.teams.count, 'team') %></td>
  <% if has_team_check? %>
    <td><%= add_player_column(player) %></td>
  <% end %>
</tr>

app/views/players/_player_table.html.erb
<table class="table table-striped table-condensed">
  <tr>
    <th>Name</th>
    <th>Position</th>
    <th>Score</th>  
    <th>Salary</th>
    <th>Value(Score Per Million)</th>
    <th>Num of Teams</th>
    <% if has_team_check? %>
      <th>Add Player</th>
    <% end %>
  </tr>
      <%= render(@players) || "There are no players yet." %>
</table>

app/views/players/_players_bar_chart.html.erb
<% data = {
    labels: [@players[0].name, @players[1].name, @players[2].name, @players[3].name, @players[4].name, @players[5].name, @players[6].name, @players[7].name, @players[8].name, @players[9].name],
    datasets: [
        {
            label: "Score Per Million Dollars",
            fillColor: "rgba(220,220,220,0.2)",
            strokeColor: "rgba(220,220,220,1)",
            pointColor: "rgba(220,220,220,1)",
            pointStrokeColor: "#fff",
            pointHighlightFill: "#fff",
            pointHighlightStroke: "rgba(220,220,220,1)",
            data: [@players[0].value, @players[1].value, @players[2].value, @players[3].value, @players[4].value, @players[5].value, @players[6].value, @players[7].value, @players[8].value, @players[9].value]
        }
    ]
} %>
<% options = {} %>
<%= bar_chart data, options %>

app/views/players/index.html.erb
<h1>Players</h1>

<%= has_team_options %>
<%= admin_options %>
<%= render "player_table" %>

app/views/players/most_valuable.html.erb
<h1>Top 10 Most Valuable Players</h1>
<% if !current_user.nil? && !current_user.team.nil? %>
  <h4>You have <%= number_to_currency(current_user.team.salary_remaining, precision: 0) %> to add players.</h4>
<% end %>
<table class="table table-striped table-condensed">
  <tr>
    <th>Name</th>
    <th>Position</th>
    <th>Score</th>  
    <th>Salary</th>
    <th>Value(Score Per Million)</th>
    <th>Add Player</th>
  </tr>
      <%= render(@players) || "There are no players yet." %>
</table>

app/views/players/new.html.erb
<h1>Create a New Player</h1>
<h4>Enter a Basketball Reference Player Profile URL</h4>
<p>For example Kobe Bryant's profile URL is http://www.basketball-reference.com/players/b/bryanko01.html</p>
<%= render 'form' %>

<h3 id="status"></h3>

<div id="playerResult">

  <h3 id="name"></h3>
  <p id="score"></p>
  <p id="salary"></p>
  <p id="value"></p>
  <p id="team_count"></p>

  <table class="table table-striped table-condensed">
    <tr>
      <th>Points</th>
      <th>Assists</th>
      <th>Rebounds</th>  
      <th>Blocks</th>
      <th>Steals</th>
      <th>Games Played</th>
    </tr>
    <tr>
      <td id="points"></td>
      <td id="assists"></td>
      <td id="rebounds"></td>
      <td id="blocks"></td>
      <td id="steals"></td>
      <td id="games_played"></td>
    </tr>
  </table>
</div>

app/views/players/show.html.erb
<%= link_to "Load Previous Player", player_path(@player.prev || 0), :class => "js-previous-player btn btn-primary", remote: true, :data => {:id => @player.prev ? @player.prev.id : 0} %>
<%= link_to "Load Next Player", player_path(@player.next || 0), :class => "js-next-player btn btn-primary", remote: true, :data => {:id => @player.next ? @player.next.id : 0} %>

<h1 id="name"><%= @player.name %>(<%= @player.position %>)</h1>
<h3 id="score">Score: <%= @player.score %></h3>
<p id="salary">Salary: <%= number_to_currency(@player.salary, precision: 0) %></p>
<p id="value">Score Per Million: <%= @player.value %></p>
<p id="team_count">Num of Teams: <%= pluralize(@player.teams.count, 'team') %></p>

<table class="table table-striped table-condensed">
  <tr>
    <th>Points</th>
    <th>Assists</th>
    <th>Rebounds</th>  
    <th>Blocks</th>
    <th>Steals</th>
    <th>Games Played</th>
  </tr>
  <tr>
    <td id="points"><%= @player.points %></td>
    <td id="assists"><%= @player.assists %></td>
    <td id="rebounds"><%= @player.rebounds %></td>
    <td id="blocks"><%= @player.blocks %></td>
    <td id="steals"><%= @player.steals %></td>
    <td id="games_played"><%= @player.games_played %></td>
  </tr>
</table>

<%= permitted_links(@player) %>