config/routes.rb
Rails.application.routes.draw do
  
  resources :leagues
  resources :leagues, only: [:show] do
    resources :teams, only: [:show, :index, :new, :create]
  end

  resources :roster_spots, only: [:create, :destroy, :update]

  resources :players

  resources :teams

  get '/reports', to: 'reports#index'
  get '/efficient', to: 'reports#most_efficient'
  get '/valuable', to: 'reports#most_valuable'
  get '/popular_leagues', to: 'reports#most_popular_leagues'
  get '/popular_players', to: 'reports#most_popular_players'
  get '/highest_scoring', to: 'reports#highest_scoring_players'
  post '/join_league', to: 'teams#join_league'
  post '/leave_league', to: 'teams#leave_league'
  post '/update_all_players', to: 'players#update_all'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'teams#index'

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
  end
  
  def most_valuable
    @players = Player.most_valuable_players
  end

  def most_popular_players
    @players = Player.most_popular_players
  end

  def most_efficient
    @teams = Team.most_efficient_teams
  end

  def most_popular_leagues
    @leagues = League.most_popular_leagues
  end

  def highest_scoring_players
    @players = Player.highest_scoring_players
  end
end

app/views/reports/highest_scoring_players.html.erb
<h1>Top 10 Highest Scoring Players</h1>
<%= display_salary_remaining %>
<%= render 'players/player_table' %>

app/views/reports/index.html.erb
<h1>Check out some reports</h1>
<h3><%= link_to "Highest Scoring Players Report", highest_scoring_path %></h3>
<h3><%= link_to "Most Popular Players Report", popular_players_path %></h3>
<h3><%= link_to "Most Valuable Players Report", valuable_path %></h3>
<h3><%= link_to "Most Popular Leagues Report", popular_leagues_path %></h3>
<h3><%= link_to "Most Efficient Teams Report", efficient_path %></h3>

app/views/reports/most_efficient.html.erb
<h1>Top 10 Most Efficient Teams</h1>
<%= create_team_link %>
<%= render "teams/team_table" %>

app/views/reports/most_popular_leagues.html.erb
<h1>Top 10 Most Popular Leagues</h1>
<% if !current_user.nil? %>
  <%= link_to "Click here to create a league", new_league_path %>
<% end %>
<%= render "leagues/league_table" %>

app/views/reports/most_popular_players.html.erb
<h1>Top 10 Most Popular Players</h1>
<%= display_salary_remaining %>
<%= render 'players/player_table' %>

app/views/reports/most_valuable.html.erb
<h1>Top 10 Most Valuable Players</h1>
<%= display_salary_remaining %>
<div class="row">
  <div class="col-md-8">
    <%= render 'players/player_table' %>
  </div>
  <div class="col-md-4">
    <%= render 'players/players_bar_chart' %>
  </div>
</div>