config/routes.rb
Rails.application.routes.draw do
  
  resources :leagues
  resources :leagues, only: [:show] do
    resources :teams, only: [:show, :index, :new, :create]
  end

  resources :roster_spots, only: [:create, :destroy, :update]

  resources :players

  resources :teams

  get '/reports', to: 'reports#index'
  get '/efficient', to: 'reports#most_efficient'
  get '/valuable', to: 'reports#most_valuable'
  get '/popular_leagues', to: 'reports#most_popular_leagues'
  get '/popular_players', to: 'reports#most_popular_players'
  get '/highest_scoring', to: 'reports#highest_scoring_players'
  post '/join_league', to: 'teams#join_league'
  post '/leave_league', to: 'teams#leave_league'
  post '/update_all_players', to: 'players#update_all'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'teams#index'

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Teams", teams_path %></li>
        <li><%= link_to "Players", players_path %></li>
        <li><%= link_to "Leagues", leagues_path %></li>
        <li><%= link_to "Reports", reports_path %></li>
        <% if !!current_user %>
          <li><%= link_to "My Team", team_path(current_user.team) unless !has_team_check? %></li>
          <li><%= link_to "Edit Account", edit_user_registration_path %></li>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Sign In", new_user_session_path %></li>
          <li><%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %></li>
        <% end %>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NbaFantasy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<header><%= render 'layouts/header' %></header>
<body>
    <% if notice %>
      <p class="alert alert-success">
        <%= notice %>
      </p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger">
        <%= alert %>
      </p>
    <% end %>

<%= yield %>

</body>
</html>

<script>
var source = "<p>Hello, my name is {{name}}. I am from {{hometown}}. I have " +
             "{{kids.length}} kids:</p>" +
             "<ul>{{#kids}}<li>{{name}} is {{age}}</li>{{/kids}}</ul>";
var template = Handlebars.compile(source);

var data = { "name": "Alan", "hometown": "Somewhere, TX",
             "kids": [{"name": "Jimmy", "age": "12"}, {"name": "Sally", "age": "4"}]};
var result = template(data);
</script>